package trc.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import trc.repository.model.TqcRulePub;
import trc.repository.model.TqcRulePubExample;

public interface TqcRulePubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    int countByExample(TqcRulePubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    int deleteByExample(TqcRulePubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    int deleteByPrimaryKey(String ruleType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    int insert(TqcRulePub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    int insertSelective(TqcRulePub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    List<TqcRulePub> selectByExample(TqcRulePubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    TqcRulePub selectByPrimaryKey(String ruleType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    int updateByExampleSelective(@Param("record") TqcRulePub record, @Param("example") TqcRulePubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    int updateByExample(@Param("record") TqcRulePub record, @Param("example") TqcRulePubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    int updateByPrimaryKeySelective(TqcRulePub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_PUB
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    int updateByPrimaryKey(TqcRulePub record);
}