package trc.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import trc.repository.model.TqcTxnMcht;
import trc.repository.model.TqcTxnMchtExample;

public interface TqcTxnMchtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    int countByExample(TqcTxnMchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    int deleteByExample(TqcTxnMchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    int insert(TqcTxnMcht record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    int insertSelective(TqcTxnMcht record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    List<TqcTxnMcht> selectByExample(TqcTxnMchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    TqcTxnMcht selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    int updateByExampleSelective(@Param("record") TqcTxnMcht record, @Param("example") TqcTxnMchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    int updateByExample(@Param("record") TqcTxnMcht record, @Param("example") TqcTxnMchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    int updateByPrimaryKeySelective(TqcTxnMcht record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_MCHT
     *
     * @mbggenerated Fri Oct 24 10:02:58 CST 2014
     */
    int updateByPrimaryKey(TqcTxnMcht record);
}