package trc.repository.model;

import java.math.BigDecimal;

public class TqcRuleAcct extends TqcRuleAcctKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String mchtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal singleLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.DAY_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal dayTotalLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.MONTH_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal monthTotalLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.RECVER
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal recver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.REMARK
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String operDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @return the value of TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getMchtName() {
        return mchtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @param mchtName the value for TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setMchtName(String mchtName) {
        this.mchtName = mchtName == null ? null : mchtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @return the value of TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @param areaCode the value for TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @return the value of TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getSingleLim() {
        return singleLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @param singleLim the value for TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setSingleLim(BigDecimal singleLim) {
        this.singleLim = singleLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.DAY_TOTAL_LIM
     *
     * @return the value of TRC.TQC_RULE_ACCT.DAY_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getDayTotalLim() {
        return dayTotalLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.DAY_TOTAL_LIM
     *
     * @param dayTotalLim the value for TRC.TQC_RULE_ACCT.DAY_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setDayTotalLim(BigDecimal dayTotalLim) {
        this.dayTotalLim = dayTotalLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.MONTH_TOTAL_LIM
     *
     * @return the value of TRC.TQC_RULE_ACCT.MONTH_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getMonthTotalLim() {
        return monthTotalLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.MONTH_TOTAL_LIM
     *
     * @param monthTotalLim the value for TRC.TQC_RULE_ACCT.MONTH_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setMonthTotalLim(BigDecimal monthTotalLim) {
        this.monthTotalLim = monthTotalLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.RECVER
     *
     * @return the value of TRC.TQC_RULE_ACCT.RECVER
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getRecver() {
        return recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.RECVER
     *
     * @param recver the value for TRC.TQC_RULE_ACCT.RECVER
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setRecver(BigDecimal recver) {
        this.recver = recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.REMARK
     *
     * @return the value of TRC.TQC_RULE_ACCT.REMARK
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.REMARK
     *
     * @param remark the value for TRC.TQC_RULE_ACCT.REMARK
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @return the value of TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @param operId the value for TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @return the value of TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @param operDate the value for TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }
}