package trc.repository.model;

import java.math.BigDecimal;

public class TqcRulePub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_PUB.RULE_TYPE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String ruleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_PUB.SINGLE_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal singleLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_PUB.DAY_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal dayTotalLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_PUB.MONTH_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal monthTotalLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_PUB.RECVER
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal recver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_PUB.REMARK
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_PUB.OPER_ID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_PUB.OPER_DATE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String operDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_PUB.RULE_TYPE
     *
     * @return the value of TRC.TQC_RULE_PUB.RULE_TYPE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_PUB.RULE_TYPE
     *
     * @param ruleType the value for TRC.TQC_RULE_PUB.RULE_TYPE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType == null ? null : ruleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_PUB.SINGLE_LIM
     *
     * @return the value of TRC.TQC_RULE_PUB.SINGLE_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getSingleLim() {
        return singleLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_PUB.SINGLE_LIM
     *
     * @param singleLim the value for TRC.TQC_RULE_PUB.SINGLE_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setSingleLim(BigDecimal singleLim) {
        this.singleLim = singleLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_PUB.DAY_TOTAL_LIM
     *
     * @return the value of TRC.TQC_RULE_PUB.DAY_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getDayTotalLim() {
        return dayTotalLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_PUB.DAY_TOTAL_LIM
     *
     * @param dayTotalLim the value for TRC.TQC_RULE_PUB.DAY_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setDayTotalLim(BigDecimal dayTotalLim) {
        this.dayTotalLim = dayTotalLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_PUB.MONTH_TOTAL_LIM
     *
     * @return the value of TRC.TQC_RULE_PUB.MONTH_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getMonthTotalLim() {
        return monthTotalLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_PUB.MONTH_TOTAL_LIM
     *
     * @param monthTotalLim the value for TRC.TQC_RULE_PUB.MONTH_TOTAL_LIM
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setMonthTotalLim(BigDecimal monthTotalLim) {
        this.monthTotalLim = monthTotalLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_PUB.RECVER
     *
     * @return the value of TRC.TQC_RULE_PUB.RECVER
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getRecver() {
        return recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_PUB.RECVER
     *
     * @param recver the value for TRC.TQC_RULE_PUB.RECVER
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setRecver(BigDecimal recver) {
        this.recver = recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_PUB.REMARK
     *
     * @return the value of TRC.TQC_RULE_PUB.REMARK
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_PUB.REMARK
     *
     * @param remark the value for TRC.TQC_RULE_PUB.REMARK
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_PUB.OPER_ID
     *
     * @return the value of TRC.TQC_RULE_PUB.OPER_ID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_PUB.OPER_ID
     *
     * @param operId the value for TRC.TQC_RULE_PUB.OPER_ID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_PUB.OPER_DATE
     *
     * @return the value of TRC.TQC_RULE_PUB.OPER_DATE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_PUB.OPER_DATE
     *
     * @param operDate the value for TRC.TQC_RULE_PUB.OPER_DATE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }
}