package trc.repository.model;

import java.math.BigDecimal;

public class TqcTxnAcct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.PKID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.MCHT_PKID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String mchtPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.TXN_DATE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.TXN_SEQNO
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String txnSeqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.MCHT_CODE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String mchtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.PRJ_CODE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String prjCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.ACCT_NO
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String acctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.TXN_AMT
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal txnAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.CHX_STATUS
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String chxStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.CHK_TIME
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String chkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.BOOK_FLAG
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String bookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.BOOK_TIME
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String bookTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.TXN_DAY_AMT_PRE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal txnDayAmtPre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.TXN_MONTH_AMT_PRE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private BigDecimal txnMonthAmtPre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.TXN_REJ_REASON
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String txnRejReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_TXN_ACCT.REMARK
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.PKID
     *
     * @return the value of TRC.TQC_TXN_ACCT.PKID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.PKID
     *
     * @param pkid the value for TRC.TQC_TXN_ACCT.PKID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.MCHT_PKID
     *
     * @return the value of TRC.TQC_TXN_ACCT.MCHT_PKID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getMchtPkid() {
        return mchtPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.MCHT_PKID
     *
     * @param mchtPkid the value for TRC.TQC_TXN_ACCT.MCHT_PKID
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setMchtPkid(String mchtPkid) {
        this.mchtPkid = mchtPkid == null ? null : mchtPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.TXN_DATE
     *
     * @return the value of TRC.TQC_TXN_ACCT.TXN_DATE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.TXN_DATE
     *
     * @param txnDate the value for TRC.TQC_TXN_ACCT.TXN_DATE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.TXN_SEQNO
     *
     * @return the value of TRC.TQC_TXN_ACCT.TXN_SEQNO
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getTxnSeqno() {
        return txnSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.TXN_SEQNO
     *
     * @param txnSeqno the value for TRC.TQC_TXN_ACCT.TXN_SEQNO
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setTxnSeqno(String txnSeqno) {
        this.txnSeqno = txnSeqno == null ? null : txnSeqno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.MCHT_CODE
     *
     * @return the value of TRC.TQC_TXN_ACCT.MCHT_CODE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getMchtCode() {
        return mchtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.MCHT_CODE
     *
     * @param mchtCode the value for TRC.TQC_TXN_ACCT.MCHT_CODE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setMchtCode(String mchtCode) {
        this.mchtCode = mchtCode == null ? null : mchtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.PRJ_CODE
     *
     * @return the value of TRC.TQC_TXN_ACCT.PRJ_CODE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getPrjCode() {
        return prjCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.PRJ_CODE
     *
     * @param prjCode the value for TRC.TQC_TXN_ACCT.PRJ_CODE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setPrjCode(String prjCode) {
        this.prjCode = prjCode == null ? null : prjCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.ACCT_NO
     *
     * @return the value of TRC.TQC_TXN_ACCT.ACCT_NO
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.ACCT_NO
     *
     * @param acctNo the value for TRC.TQC_TXN_ACCT.ACCT_NO
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.TXN_AMT
     *
     * @return the value of TRC.TQC_TXN_ACCT.TXN_AMT
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getTxnAmt() {
        return txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.TXN_AMT
     *
     * @param txnAmt the value for TRC.TQC_TXN_ACCT.TXN_AMT
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setTxnAmt(BigDecimal txnAmt) {
        this.txnAmt = txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.CHX_STATUS
     *
     * @return the value of TRC.TQC_TXN_ACCT.CHX_STATUS
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getChxStatus() {
        return chxStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.CHX_STATUS
     *
     * @param chxStatus the value for TRC.TQC_TXN_ACCT.CHX_STATUS
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setChxStatus(String chxStatus) {
        this.chxStatus = chxStatus == null ? null : chxStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.CHK_TIME
     *
     * @return the value of TRC.TQC_TXN_ACCT.CHK_TIME
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getChkTime() {
        return chkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.CHK_TIME
     *
     * @param chkTime the value for TRC.TQC_TXN_ACCT.CHK_TIME
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setChkTime(String chkTime) {
        this.chkTime = chkTime == null ? null : chkTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.BOOK_FLAG
     *
     * @return the value of TRC.TQC_TXN_ACCT.BOOK_FLAG
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getBookFlag() {
        return bookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.BOOK_FLAG
     *
     * @param bookFlag the value for TRC.TQC_TXN_ACCT.BOOK_FLAG
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setBookFlag(String bookFlag) {
        this.bookFlag = bookFlag == null ? null : bookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.BOOK_TIME
     *
     * @return the value of TRC.TQC_TXN_ACCT.BOOK_TIME
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getBookTime() {
        return bookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.BOOK_TIME
     *
     * @param bookTime the value for TRC.TQC_TXN_ACCT.BOOK_TIME
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setBookTime(String bookTime) {
        this.bookTime = bookTime == null ? null : bookTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.TXN_DAY_AMT_PRE
     *
     * @return the value of TRC.TQC_TXN_ACCT.TXN_DAY_AMT_PRE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getTxnDayAmtPre() {
        return txnDayAmtPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.TXN_DAY_AMT_PRE
     *
     * @param txnDayAmtPre the value for TRC.TQC_TXN_ACCT.TXN_DAY_AMT_PRE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setTxnDayAmtPre(BigDecimal txnDayAmtPre) {
        this.txnDayAmtPre = txnDayAmtPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.TXN_MONTH_AMT_PRE
     *
     * @return the value of TRC.TQC_TXN_ACCT.TXN_MONTH_AMT_PRE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public BigDecimal getTxnMonthAmtPre() {
        return txnMonthAmtPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.TXN_MONTH_AMT_PRE
     *
     * @param txnMonthAmtPre the value for TRC.TQC_TXN_ACCT.TXN_MONTH_AMT_PRE
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setTxnMonthAmtPre(BigDecimal txnMonthAmtPre) {
        this.txnMonthAmtPre = txnMonthAmtPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.TXN_REJ_REASON
     *
     * @return the value of TRC.TQC_TXN_ACCT.TXN_REJ_REASON
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getTxnRejReason() {
        return txnRejReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.TXN_REJ_REASON
     *
     * @param txnRejReason the value for TRC.TQC_TXN_ACCT.TXN_REJ_REASON
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setTxnRejReason(String txnRejReason) {
        this.txnRejReason = txnRejReason == null ? null : txnRejReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_TXN_ACCT.REMARK
     *
     * @return the value of TRC.TQC_TXN_ACCT.REMARK
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_TXN_ACCT.REMARK
     *
     * @param remark the value for TRC.TQC_TXN_ACCT.REMARK
     *
     * @mbggenerated Wed Oct 15 16:40:20 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}